version: "3.8"

services:
  camunda-server:
    build: ./inzagher-camunda-server
    image: "inzagher/camunda-sandbox-server"
    container_name: "camunda-sandbox-server"
    ports:
      - "8090:8090"
  camunda-client:
    build: ./inzagher-camunda-client
    image: "inzagher/camunda-sandbox-client"
    container_name: "camunda-sandbox-client"
    depends_on:
      - "camunda-server"
    ports:
      - "8095:8095"